const ops: [string, string, any][] = [
["SearchClustersMcp",`query SearchClustersMcp($searchTerm: String!, $pageSize: Int, $pageCursor: String) { searchClusters(searchTerm: $searchTerm, meta: { pageSize: $pageSize, pageCursor: $pageCursor }) { items { id name slug description isPrivate coverImageUrl numberOfElements owner { id username fullName } } meta { count nextPageCursor } } }`,{searchTerm:"x",pageSize:1}],
["GlobalSearchMcp",`query GlobalSearchMcp($searchTerm: String!, $pageSize: Int, $pageCursor: String) { search(searchTerm: $searchTerm) { clusters(meta: { pageSize: $pageSize, pageCursor: $pageCursor }) { items { id name slug isPrivate ownerId coverImageUrl collaboratorsCount } meta { count nextPageCursor } } users(meta: { pageSize: $pageSize }) { items { id name username avatarUrl isPremium isVerifiedProfile } meta { count nextPageCursor } } elements(meta: { pageSize: $pageSize }) { items { id } meta { count nextPageCursor } } } }`,{searchTerm:"x",pageSize:1}],
["UpdateClusterMcp",`mutation UpdateClusterMcp($id: ClusterId!, $name: String!, $isPrivate: Boolean!, $description: String, $coverImageElementId: ElementId) { cluster { update(input: { id: $id, name: $name, isPrivate: $isPrivate, description: $description, coverImageElementId: $coverImageElementId }) { success } } }`,{id:1,name:"n",isPrivate:false}],
["EditClusterMcp",`mutation EditClusterMcp($id: ClusterId!, $name: String!, $isPrivate: Boolean!, $description: String, $coverImageElementId: ElementId) { cluster { edit(input: { id: $id, name: $name, isPrivate: $isPrivate, description: $description, coverImageElementId: $coverImageElementId }) { id name slug description isPrivate coverImageUrl numberOfElements } } }`,{id:1,name:"n",isPrivate:false}],
["DeleteClustersMcp",`mutation DeleteClustersMcp($userId: UserId!, $clusterIds: [ClusterId!]!) { cluster { delete(input: { userId: $userId, clusterIds: $clusterIds }) { success } } }`,{userId:1,clusterIds:[1]}],
["DeleteClusterMcp",`mutation DeleteClusterMcp($userId: UserId!, $id: ClusterId!) { cluster { deleteCluster(input: { userId: $userId, id: $id }) { success } } }`,{userId:1,id:1}],
["ImportFromPageMcp",`mutation ImportFromPageMcp($sourceUrl: String!, $userId: UserId, $clusterId: ClusterId) { import { request(input: { sourceUrl: $sourceUrl, userId: $userId, clusterId: $clusterId }) { success } } }`,{sourceUrl:"https://x.com"}],
["ImportFromUrlsMcp",`mutation ImportFromUrlsMcp($sourceUrls: [String!]!, $userId: UserId, $clusterId: ClusterId) { import { requestFromUrls(input: { sourceUrls: $sourceUrls, userId: $userId, clusterId: $clusterId }) { success } } }`,{sourceUrls:["https://x.com/a.jpg"]}],
["CreateElementMcp",`mutation CreateElementMcp($userId: UserId!, $url: String, $sourceUrl: String, $text: String, $clusterId: ClusterId) { element { create(input: { userId: $userId, url: $url, sourceUrl: $sourceUrl, text: $text, clusterId: $clusterId }) { id __typename } } }`,{userId:1,url:"https://x.com/a.jpg"}],
["RemoveFromClusterMcp",`mutation RemoveFromClusterMcp($userId: UserId!, $clusterId: ClusterId!, $elementIds: [ElementId!]!) { element { disconnectElementsFromCluster(input: { userId: $userId, clusterId: $clusterId, elementIds: $elementIds }) { success } } }`,{userId:1,clusterId:1,elementIds:[1]}],
["DeleteElementsMcp",`mutation DeleteElementsMcp($userId: UserId!, $elementIds: [ElementId!]!) { element { deleteElements(input: { userId: $userId, elementIds: $elementIds }) { success } } }`,{userId:1,elementIds:[1]}],
["FollowClusterMcp",`mutation FollowClusterMcp($userId: UserId!, $clusterId: ClusterId!) { cluster { follow(input: { userId: $userId, clusterId: $clusterId }) { success } } }`,{userId:1,clusterId:1}],
["UnfollowClusterMcp",`mutation UnfollowClusterMcp($userId: UserId!, $clusterId: ClusterId!) { cluster { unfollow(input: { userId: $userId, clusterId: $clusterId }) { success } } }`,{userId:1,clusterId:1}],
["FollowUserMcp",`mutation FollowUserMcp($followerId: UserId!, $followeeId: UserId!) { userFollow { create(input: { followerId: $followerId, followeeId: $followeeId }) { success } } }`,{followerId:1,followeeId:2}],
["UnfollowUserMcp",`mutation UnfollowUserMcp($followerId: UserId!, $followeeId: UserId!) { userFollow { delete(input: { followerId: $followerId, followeeId: $followeeId }) { success } } }`,{followerId:1,followeeId:2}],
["CreateSubclusterMcp",`mutation CreateSubclusterMcp($userId: UserId!, $name: String!, $parentClusterId: ClusterId!, $isPrivate: Boolean) { cluster { create(input: { userId: $userId, name: $name, parentClusterId: $parentClusterId, isPrivate: $isPrivate }) { id name slug parentClusterId } } }`,{userId:1,name:"n",parentClusterId:1}],
["AttachToParentMcp",`mutation AttachToParentMcp($userId: UserId!, $clusterId: ClusterId!, $parentClusterId: ClusterId!) { cluster { attachToParent(input: { userId: $userId, clusterId: $clusterId, parentClusterId: $parentClusterId }) { success } } }`,{userId:1,clusterId:1,parentClusterId:2}],
["DetachFromParentMcp",`mutation DetachFromParentMcp($userId: UserId!, $clusterId: ClusterId!) { cluster { detachFromParent(input: { userId: $userId, clusterId: $clusterId }) { success } } }`,{userId:1,clusterId:1}],
["InviteCollaboratorMcp",`mutation InviteCollaboratorMcp($clusterId: ClusterId!, $email: String, $userId: UserId) { cluster { inviteCollaborator(input: { clusterId: $clusterId, email: $email, userId: $userId }) { success } } }`,{clusterId:1,email:"a@b.co"}],
["CreateClusterInviteLinkMcp",`mutation CreateClusterInviteLinkMcp($clusterId: ClusterId!) { cluster { createInviteLink(input: { clusterId: $clusterId }) { __typename } } }`,{clusterId:1}],
["RemoveCollaboratorMcp",`mutation RemoveCollaboratorMcp($clusterId: ClusterId!, $userId: UserId!) { cluster { deleteCollaborator(input: { clusterId: $clusterId, userId: $userId }) { success } } }`,{clusterId:1,userId:1}],
["LeaveCollaborationMcp",`mutation LeaveCollaborationMcp($clusterId: ClusterId!, $userId: UserId!) { cluster { leaveCollaboration(input: { clusterId: $clusterId, userId: $userId }) { success } } }`,{clusterId:1,userId:1}],
["SetElementCaptionMcp",`mutation SetElementCaptionMcp($elementId: ElementId!, $text: String!) { element { updateCaption(input: { elementId: $elementId, text: $text }) { success } } }`,{elementId:1,text:"t"}],
["ClearElementCaptionMcp",`mutation ClearElementCaptionMcp($elementIds: [ElementId!]) { element { clearCaption(input: { elementIds: $elementIds }) { success } } }`,{elementIds:[1]}],
["DislikeElementsMcp",`mutation DislikeElementsMcp($userId: UserId!, $elementIds: [ElementId!]!) { element { dislike(input: { userId: $userId, elementIds: $elementIds }) { success } } }`,{userId:1,elementIds:[1]}],
["PinClusterMcp",`mutation PinClusterMcp($userId: UserId!, $clusterId: ClusterId!) { userProfile { pinCluster(input: { userId: $userId, clusterId: $clusterId }) { success } } }`,{userId:1,clusterId:1}],
["UnpinClusterMcp",`mutation UnpinClusterMcp($userId: UserId!, $clusterId: ClusterId!) { userProfile { unpinCluster(input: { userId: $userId, clusterId: $clusterId }) { success } } }`,{userId:1,clusterId:1}],
["CreateImageElementMcp",`mutation CreateImageElementMcp($userId: UserId!, $url: String!, $width: Int!, $height: Int!, $clusterId: ClusterId) { element { create(input: { userId: $userId, image: { url: $url, width: $width, height: $height }, clusterId: $clusterId }) { id __typename } } }`,{userId:1,url:"https://x/a.jpg",width:1,height:1}],
["BlockUserMcp",`mutation BlockUserMcp($userId: UserId!, $userToBlockId: UserId!) { user { blockOtherUser(input: { userId: $userId, userToBlockId: $userToBlockId }) { success } } }`,{userId:1,userToBlockId:2}],
];
for (const [name, query, variables] of ops) {
  const res = await fetch(`https://api.cosmos.so/graphql?q=${name}`, { method:"POST",
    headers:{ "content-type":"application/json","x-client-name":"cosmos-web",origin:"https://www.cosmos.so",referer:"https://www.cosmos.so/",accept:"application/graphql-response+json,application/json;q=0.9"},
    body: JSON.stringify({operationName:name, query, variables}) });
  const b: any = await res.json();
  const errs = (b.errors ?? []).filter((e:any)=>e?.extensions?.code!=="AUTHENTICATION");
  const ok = b.data || errs.length===0;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}`, ok ? "" : JSON.stringify(errs.map((e:any)=>`${e.extensions?.code}: ${e.message}`)));
  await new Promise(r=>setTimeout(r,150));
}
